# Generated by Django 2.2 on 2020-06-07 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20200607_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
