# Generated by Django 2.2 on 2020-06-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_information_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
